spring:
  application:
    name: twitter-clone-backend
  profiles:
    active: dev
    
server:
  port: 8280
    
    
---

spring:
  profiles: dev
  

  data:
    mongodb:
      host: localhost
      port: 27017
      database: twitter-dev-db
      
      
security:
  oauth2:
    client:
      client-id: R2dpxQ3vPrtfgF72
      client-secret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
      access-token-uri: http://localhost:8081/oauth/token
      user-authorization-uri: http://localhost:8081/oauth/authorize
      grant-type: client-credentials
      scope: all
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token